// Per-tab instructional copy shown in the simulator's Help panel. Pure data.
export const HELP = {
  overview: {
    title: "Overview",
    intro: "A read-only summary. Nothing here is editable — every number is driven by what you enter on the other tabs.",
    points: [
      ["The five stat cards", "Net worth is assets minus debts today. Monthly surplus is income minus living costs, before debt payments and investing. Cash runway is how long your cash and savings alone would cover spending with no income arriving at all — under three months turns red. The debt-free and independence dates come from the projection below."],
      ["Inflation", "Every rate you enter — returns, APRs, raises, a promotion's new salary — is nominal, and the projection runs in today's dollars, so each one is converted to a real rate first: 7% growth against 2.5% inflation compounds at 4.39% here. Your spending holds its value in the same way. Loan payments are the deliberate exception, because a fixed payment doesn't rise with prices — in today's money it shrinks year after year, which is a real and usually welcome effect."],
      ["Show future dollars", "A display toggle, not a change to the simulation. It re-labels the charts in the money of the day rather than today's, which is what a future statement would actually show. No date moves, because the independence target inflates at exactly the same rate the balances do — which is why the target is drawn as a rising line in that mode rather than a flat one."],
      ["Net worth projection", "Simulates your accounts, debts, income and spending forward week by week for up to 40 years. Amber is net worth, green is investments, red is total debt."],
      ["Reading the chart", "Scroll or pinch to zoom, drag to pan, or use the 1Y / 5Y / Max buttons. Hover any point for exact figures on that date."],
      ["Include future promotions", "A toggle under the net worth chart. Switch it off to re-run the whole projection on today's salary, with every planned promotion ignored — the fastest way to see what you're counting on them for. The note beside it reports the net worth gap at the chart's current zoom, plus how much sooner they get you to debt-free and financial independence. The toggle applies everywhere, not just this chart."],
      ["What would it take?", "Runs the projection in reverse. Pick a target — debt-free by a date, independent by a date, or a survival percentage — and what you'd change to get there, and it searches for the amount that meets it. It will tell you when it can't: an unreachable target says so rather than handing back a number that doesn't work, and a lever that doesn't move the target says that too. Cutting spending won't clear a loan sooner, for instance, because the freed money piles up in checking unless a payment carries it to the debt."],
      ["What moves the date", "Nudges each input on its own and ranks how far your independence date moves. The ordering is the useful part, and it's usually not the one you'd guess — on the starting example a single point of inflation costs more than a year, while $200/mo more invested buys about a month."],
      ["What happens when", "Every dated thing the projection knows, in order: each loan clearing, net worth passing round numbers, debt-free, independence, and any dates inferred from your age. Nothing here is a separate calculation — it's the same projection the charts draw, so the two can't disagree."],
      ["Undo and history", "Every edit is reversible — ⌘Z or the toolbar button, ⌘⇧Z to redo. A burst of typing counts as one step, but adding or deleting a row is always its own, so undo can't quietly skip past a deletion. Separately, the app keeps a copy of your whole plan once a day under Scenarios, so a bad edit or a bad import is recoverable even if you never saved a scenario. Restoring one is itself undoable."],
      ["Where you've actually been", "Those daily copies record what your net worth really was, drawn as cyan points on the chart, and what the plan was predicting at the time. That's where the note under the chart comes from: whether independence has moved closer or further away since the last time you looked, which a single projection can't tell you."],
      ["Scenarios", "Save the whole plan under a name from the toolbar, then pick one to compare against. Its net worth appears as a dashed second line, with a table of how far apart the two plans put each milestone. Saving doesn't change what you're working on, and loading one asks first."],
      ["Every account & debt over time", "The same simulation, but with one line per account and a dashed line per debt, so you can see which account is doing the work — or running dry."],
      ["Warnings", "A red banner appears if you're spending more than you earn, or if any single account goes negative at some point in the projection."],
    ],
  },
  accounts: {
    title: "Accounts",
    intro: "Your balance sheet — everything you own. This is where you set starting balances and expected returns.",
    points: [
      ["Add your accounts", "Give each one a name, a type, today's balance, and an expected annual return. Picking a type fills in a sensible default rate, which you can then override."],
      ["Balance as of (optional)", "Leave blank if the balance is accurate today. Set a future date to freeze the account until then — useful for one you haven't opened yet. Set a past date (a recent statement balance, say) and it's caught up to today using your normal income, expenses and payments in the meantime."],
      ["Types matter", "Brokerage and Retirement count as 'invested' for the asset mix and the independence target. Savings, Checking, Cash and Other asset don't."],
      ["Tax treatment", "Separate from the type, and it decides three things: whether growth is docked for tax each year (taxable investments are), whether a withdrawal is taxed (tax-deferred money is, so it counts for less toward independence), and whether it can be reached before 59½ (only taxable money can). It's defaulted from the type — Retirement becomes tax-deferred — so an account holding both Roth and traditional money is worth splitting into two."],
      ["Enter returns as nominal, constant rates", "Enter the rate you'd quote — 7% for a stock portfolio, 4% for a savings account. The projection deflates it by your inflation setting on the Overview tab and applies the result every week, forever. It does not model volatility, crashes, or tax on gains. A 0% account genuinely loses ground here, because holding cash does."],
      ["Caps and sweeping (optional)", "Set a cap to stop cash idling in an account. Anything above the cap is swept to the destination you pick — another account, or a debt to pay down."],
      ["Watch the cap warning", "The hint under each cap tells you what that account's heaviest month costs. A cap below that number will overdraw the account, and it turns red to say so."],
    ],
  },
  cashflow: {
    title: "Cash flow",
    intro: "Everything that moves money, with dates. This tab drives almost the entire projection, so it's worth getting right.",
    points: [
      ["Income", "Enter take-home pay per paycheck and how often it arrives. Enter gross separately — as an annual salary or per paycheck — since percentage-based deductions are calculated off gross."],
      ["Pre-tax deductions and match", "401k contributions never reach take-home, so they're added on top and sent straight to the account you choose. An employer match of '100% up to 3%' means every dollar matched, capped at the first 3% of gross."],
      ["Typed take-home, or derived from brackets", "Each income can either use the take-home figure you type — the default, and what every saved plan keeps — or derive it from your gross through the federal brackets, FICA, and a flat state rate you set. In typed mode the card still shows what the brackets would say, which is the quickest check on a figure you entered from memory. In derived mode a promotion needs no tax rate of its own: a bigger gross produces its own take-home, taxed at the rate the extra actually lands in."],
      ["Guaranteed retirement income", "Social Security or a pension is income that arrives whether or not you have a portfolio, so it does two things: it appears in cash flow from its start date, and it lowers the independence target by the spending it covers. Because it only starts on that date, the target also carries the capital to cover the gap yourself until then — which is why the target line slopes down toward the date rather than dropping in one step."],
      ["The annual limit", "The IRS caps what you can elect into a 401k or 403b each year. Contributions stop once they reach the figure you set and start again in January, and anything marked as not counting toward it — an HSA, insurance — is left alone. If you'd hit the cap early, the note says when: a match paid per paycheck stops when the contribution it rides on stops, so front-loading can quietly forfeit part of the year's match unless your plan trues up. The limit applies per income source, counts from today rather than from January (so it doesn't know what you've already contributed this year), and it's editable because the IRS moves it most years."],
      ["Raises, promotions and bonuses", "A raise compounds annually. A promotion is a step change to a new salary on a date — enter the new gross and a tax rate (prefilled from today's rate) and take-home is worked out for you. A bonus lands once a year on its own date and can be a flat amount or a percentage of salary."],
      ["Splitting a paycheck", "Route a percentage or fixed amount to other accounts. The first row in the list receives whatever is left over."],
      ["Expenses", "Set an amount, how often, and which account or credit card it comes from. Add an end date for anything temporary — tuition, a lease — so it doesn't inflate your long-run independence target."],
      ["Payments and transfers", "Payments reduce debt; transfers move money between your own accounts. A card payment can be set to 'pay in full' so it clears whatever was charged that month."],
    ],
  },
  debt: {
    title: "Debt",
    intro: "Loans and cards, and how fast your plan clears them. Balances are edited here; the payments that clear them live on the Cash flow tab.",
    points: [
      ["Balance decay", "Amber is your actual plan. Cyan is what would happen paying only the minimums. The gap between them is what your extra payments are buying you."],
      ["Interest saved and time saved", "Both stat cards compare your plan against that minimums-only path."],
      ["Payoff order", "Pick the strategy at the top of the loan list. Avalanche sends any surplus to your highest-rate loan, which costs the least interest. Snowball sends it to your smallest balance, which clears individual loans sooner. The note underneath prices the difference both ways, since the cheaper plan isn't always the one that's easiest to stick to."],
      ["By payment or by term", "A loan can be described either way. Type a minimum payment and the card tells you how long that takes — or how long it never takes, if the payment doesn't cover the interest. Switch to \"by term\", enter the months, and the payment is derived instead."],
      ["Interest start date", "Interest accrues from this date. Push it into the future for a subsidised loan sitting in deferment, and it won't accrue until then."],
      ["Credit cards behave differently", "A card only charges interest on a balance you carry. Pay it in full each month and it costs nothing — so cards are excluded from the debt-free date calculation."],
      ["Next $200: debt or investing?", "The oldest question in personal finance, answered with your plan rather than a rule of thumb. It compares the rates — your loan's APR after inflation against your blended real return — and then runs the whole projection both ways, because the rates alone don't capture what freeing a payment early does to everything downstream. When the two land within a percent of each other it says so, rather than dressing up rounding as advice."],
      ["Changing the plan", "To pay debt down faster, edit or add a payment on the Cash flow tab. This tab shows the result."],
    ],
  },
  invest: {
    title: "Invest",
    intro: "Long-run growth and what it would take to stop needing a salary.",
    points: [
      ["Portfolio growth", "Splits your projected investment balance into money you contributed versus returns earned on top of it."],
      ["Independence target", "Your annual recurring spending divided by your withdrawal rate. At the default 4%, that's 25× your yearly costs."],
      ["Expenses that end don't count", "Anything with an end date inside the next ten years is treated as temporary and left out of the target, since it isn't a forever cost."],
      ["Adjust the withdrawal rate", "Lower it for a more conservative target that needs a bigger portfolio; raise it for the opposite."],
      ["Spendable, not just net worth", "The independence date is measured against what the balance sheet is worth to spend. A tax-deferred dollar is docked the withdrawal rate you set, because that's what the IRS takes on the way out, and taxable investments lose a little return every year to tax on distributions. Both are set here; which accounts they apply to is set on the Accounts tab."],
      ["The bridge to 59½", "Enter a birth year and the tab checks something the date alone hides: whether enough of your money is reachable before retirement accounts open. Independence at 47 with everything in a 401(k) isn't independence — the bridge line says how much you'd need outside those accounts, and how much you're short."],
      ["Monte Carlo: does the money last?", "Runs your plan hundreds of times with randomized returns instead of one constant rate. Up to the retirement date it follows the same contributions as the chart above; after it, contributions stop and the portfolio starts paying out. The headline number is the share of those runs where the money never ran out."],
      ["Sequence-of-returns risk", "This is the question the deterministic chart can't answer. Two portfolios with the same average return can end very differently depending on when the bad years land: a crash early in retirement is withdrawn from as well as fallen through, and may never recover. It's why raising volatility barely moves the median line but cuts the survival number sharply."],
      ["Retirement date and horizon", "By default retirement starts on the projection's own independence date and the money has to last thirty years, or to the age you set if you've entered a birth year. Override the date to ask a different question — \"what if I stopped at 50?\" — and watch what it does to the odds."],
      ["What it doesn't model", "Withdrawals are held constant in today's dollars, with no spending flexibility. A real retiree cuts back after a bad year, and that alone rescues many of the runs counted here as failures. Treat the percentage as a stress test, not a verdict."],
      ["A projection, not advice", "The chart above this one holds returns constant — today's dollars, real returns after your inflation setting, no tax or volatility. The Monte Carlo chart relaxes the volatility assumption only, as one blended portfolio at that same real return; neither models sequence-of-returns risk in retirement or fees. Treat the dates as a direction of travel, not a promise."],
    ],
  },
};

